//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCorta4PrograV.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaCriollitaEntities : DbContext
    {
        public LaCriollitaEntities()
            : base("name=LaCriollitaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Platillos> Platillos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
