//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareaCorta4.DA
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Platillos
    {
        public int idPlatillo { get; set; }
        public string Nombre { get; set; }
        public int idEstado { get; set; }
        public int idCategoria { get; set; }
        public decimal Costo { get; set; }
        [JsonIgnore]
        public virtual Categorias Categorias { get; set; }
        [JsonIgnore]
        public virtual Estados Estados { get; set; }
    }
}
